### ISSUE TITLE
Student Report Generation Giving Application Error

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1276] opened 2017-11-27 14:57 UTC
An assistant principal was trying to generate a student report, it took a while, and then gave the Application Error screen.  I've tried it as well and it provided the same error.

**Comment by alexsoble** [comment] 2017-11-27 19:05
@snoopyuri Yup, confirming this error with the Student Report.

**Comment by alexsoble** [comment] 2017-11-27 19:06
The logs show it's associated with memory errors:

```
2017-11-27T19:03:46.329283+00:00 heroku[web.1]: Process running mem=878M(170.9%)
2017-11-27T19:03:46.329544+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-27T19:04:08.699605+00:00 heroku[web.1]: Process running mem=919M(176.7%)
2017-11-27T19:04:08.699801+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2017-11-27T19:04:12.952315+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET 
```

**Comment by jhilde** [comment] 2017-11-27 19:08
Ughh! Thanks @alexsoble 

I can take a bit of a look tonight. @snoopyuri can you send me the student information so I can reproduce it?

**Comment by alexsoble** [comment] 2017-11-27 19:09
I tried restarting the dynos since that's brought down memory usage before, didn't heal the problem.

Checking the Heroku dashboard, it looks like there was a spike in memory usage today around 7AM and it hasn't gone down since:

![screen shot 2017-11-27 at 1 07 52 pm](https://user-images.githubusercontent.com/3209501/33284289-2c7c41da-d374-11e7-91d7-88ef41568b48.png)

**Comment by alexsoble** [comment] 2017-11-27 19:09
@jhilde I don't think you need any particular student's information, I picked a student at random and the student report was down.

**Comment by jhilde** [comment] 2017-11-27 19:13
Thanks @alexsoble. I was thinking it may have to do with more notes, behavior incidents, services etc.

So maybe it isn't student report specific? Other than the pdf generation hogs memory?

**Comment by alexsoble** [comment] 2017-11-27 19:15
@jhilde What I'm seeing right now by experimenting on the production app and looking at Heroku is that all the HTML pages are loading, none of the PDF student reports are loading, and memory usage is very high.

**Comment by alexsoble** [comment] 2017-11-27 19:16
Memory use dropped to decent levels (presumably caused by the Heroku app restart) but I'm still getting Application Errors when I try to open Student Reports. 

![screen shot 2017-11-27 at 1 15 24 pm](https://user-images.githubusercontent.com/3209501/33284534-0ccd68c2-d375-11e7-859d-51d4e271a38e.png)

**Comment by alexsoble** [comment] 2017-11-27 19:18
Hmm, even though the little line on the Heroku metrics went way down, the logs still say that memory usage is at 152.4%.

**Comment by alexsoble** [comment] 2017-11-27 19:25
We did a bunch of work to try to reduce memory use last year, with fairly limited results. I did a little looking around for new resources and found this blog post from June on debugging memory issues on Heroku: https://blog.codeship.com/debugging-a-memory-leak-on-heroku/

It has a lot of useful-looking ideas and strategies that we haven't tried before!

**Comment by edavidsonsawyer** [comment] 2017-11-27 20:40
FWIW @alexsoble @jhilde, I happened to notice this demo site as well this morning, so it may not be related to the specific Heroku instance.

**Comment by alexsoble** [comment] 2017-11-27 22:03
@edavidsonsawyer Ooooh that's really interesting. That said I don't see anything on https://status.heroku.com/.

**Comment by jhilde** [comment] 2017-11-27 22:08
@alexsoble @edavidsonsawyer Can either of you confirm you can generate pdfs locally? Been a bit since I've run Student Insights but PDF generation is hanging on my machine.

**Comment by alexsoble** [comment] 2017-11-27 22:12
@jhilde Investigating!

**Comment by alexsoble** [comment] 2017-11-27 22:13
@jhilde Hanging for me as well! So maybe it's not just a memory issue!! Good thought Justin!

**Comment by jhilde** [comment] 2017-11-27 22:14
I'll be away for a bit but will look later tonight.

**Comment by kevinrobinson** [comment] 2017-11-28 00:58
Hi pals!  I caught up with this thread, here's some debugging info and a fix.

First, I don't think there's good evidence that this is related to memory usage.  In [this comment](https://github.com/studentinsights/studentinsights/issues/1276#issuecomment-347290543), the log messages have errors about memory usage, but those are always there.  We have memory usage errors in the logs constantly, and this is something we should improve but seeing those log messages being next to the request doesn't mean they're causing the problem.  The logs in that comment show that the actual immediate problem is "Request timeout."  @edavidsonsawyer's comment that this is impacting the demo site as well suggests it is more likely a code bug than something about the performance of particular dynos.  Finally, it looks like we went and upgraded to more powerful dynos in https://github.com/studentinsights/studentinsights/issues/1279 but the problem is still unresolved and the request still times out after 60 seconds as @alexsoble noted in https://github.com/studentinsights/studentinsights/issues/1279#issuecomment-347370245.  So that wasn't the problem here.

Second, the error in the logs says it's a "Request timeout" and trying this manually now, the logs give another data point on what's wrong.  The test URL I used is the first student on the HS page.  These are the logs generated:

```
2017-11-28T00:31:00.286712+00:00 app[web.1]: [784ef547-bc2b-44b3-9d9c-a4317eea33d2] Started GET "/students/xyz/student_report.pdf?sections=notes,services,attendance,discipline_incidents,assessments&from_date=08/15/2016&to_date=11/27/2017" for x.y.z at 2017-11-28 00:31:00 +0000
2017-11-28T00:31:00.321836+00:00 app[web.1]: [784ef547-bc2b-44b3-9d9c-a4317eea33d2] Processing by StudentsController#student_report as PDF
2017-11-28T00:31:00.322311+00:00 app[web.1]: [784ef547-bc2b-44b3-9d9c-a4317eea33d2]   Parameters: {"sections"=>"notes,services,attendance,discipline_incidents,assessments", "from_date"=>"08/15/2016", "to_date"=>"11/27/2017", "id"=>"xyz"}
2017-11-28T00:31:00.772765+00:00 app[web.1]: [784ef547-bc2b-44b3-9d9c-a4317eea33d2] ***************WICKED***************
2017-11-28T00:31:00.773911+00:00 app[web.1]: [784ef547-bc2b-44b3-9d9c-a4317eea33d2]   Rendering students/student_report.pdf.erb
2017-11-28T00:31:01.689895+00:00 app[web.1]: [784ef547-bc2b-44b3-9d9c-a4317eea33d2]   Rendered students/student_report.pdf.erb (915.8ms)
...
2017-11-28T00:31:30.274082+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/students/xyz/student_report.pdf?sections=notes,services,attendance,discipline_incidents,assessments&from_date=08/15/2016&to_date=11/27/2017" host=somerville.studentinsights.org request_id=784ef547-bc2b-44b3-9d9c-a4317eea33d2 fwd="x.y.z" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
```

So parsing that, you can see that Rails finishes rendering the PDF for the request in less than a second.  Then, 29 seconds later, Heroku times out.  This makes it seem like something is preventing the request from completing after rendering.  For the student report PDF, there's code in [Rails](https://github.com/studentinsights/studentinsights/blob/master/app/controllers/students_controller.rb#L71) that tells wkhtmltopdf to wait to return until a particular JS value to be set, and then [JS code](https://github.com/studentinsights/studentinsights/blob/master/app/assets/javascripts/student_profile/pdf/student_profile_pdf.js#L138) that sets that value.  So it seems likely something there is what's causing the request not to complete (even after Rails has finished rendering).  We can add a `debug=true` param to the URL in production to render the page as HTML and see what we see:

<img width="973" alt="screen shot 2017-11-27 at 7 35 56 pm" src="https://user-images.githubusercontent.com/1056957/33296979-844d5a06-d3ac-11e7-89ba-f0508b13569c.png">

This shows a JS error halted the execution of JS on the page.  That's the problem.  This means the JS code never sets the "I'm done rendering" value that wkhtmltopdf is waiting for, and so the process just sits and waits forever until Heroku ultimately times out the request after 60 seconds.

Looking at that code, it's from a call to `this.yearAxisCaption` within `yearCategories` in `graph_helpers.js`.  It's trying to call a method that doesn't exist after the refactoring to make these plain functions that were exported individually.  Looking at the git history for that file it was introduced six days ago in #1261 [here](https://github.com/studentinsights/studentinsights/pull/1261/files#diff-1258146de6a83e93d0a162e2b6ae69b8).  The bug can be reproduced locally for any student, and changing that line resolves the issue locally.  Here's a pull request with the fix: https://github.com/studentinsights/studentinsights/pull/1283

Backing up, this is a particularly tricky bug to catch in tests because it exists at the seams between systems.  But a smoke test on the JS code for the profile could have caught this and would be cheap to add.  That'd be a good action out of this.  Another thing is that it looks like we upgraded dynos, and so my vote would be to either measure what user-facing impact that has or to downgrade back to cheaper dynos if there is not impact.

**Comment by jhilde** [comment] 2017-11-28 01:05
Thanks @kevinrobinson. I'll finally add a smoke test for student PDF. I'll likely use the debug option to test some basic content and test that a pdf is returned for non-debug option.

**Comment by kevinrobinson** [comment] 2017-11-28 01:09
@jhilde Sounds good!  I was thinking of a smoke test on just the JS code that should run.  If you can figure out how to do it in RSpec end-to-end that seems great too, I'm just not sure how to do that off the top of my head.

**Comment by kevinrobinson** [comment] 2017-11-28 01:11
Also, another good improvement would be this: https://github.com/studentinsights/studentinsights/issues/1284

**Comment by alexsoble** [comment] 2017-11-28 01:17
Fixed in prod by @kevinrobinson. Just deployed and verified the fix. 👍  Sorry for leading folks down a red herring path with the memory errors!

**Closed by alexsoble** 2017-11-28 01:17 UTC

**Comment by kevinrobinson** [comment] 2017-11-28 01:19
Thanks for deploying!  Bugs are hard, and the handoff here between Rails/wkhtmltopdf/JS is especially confusing.  Those memory errors are prime for red herrings too, it'd be great to figure that out finally one of these days too, but if they're not really causing problems at the moment...

**Comment by alexsoble** [comment] 2017-11-28 01:39
@kevinrobinson Check out the app with the regular-sized dynos, feels perceptively faster to me. Also our Heroku memory metrics graph right now: 

![screen shot 2017-11-27 at 7 39 26 pm](https://user-images.githubusercontent.com/3209501/33298225-b9facca8-d3aa-11e7-85d1-78e0a01338ac.png)
