### ISSUE TITLE
Investigate discrepancy in discipline incidents between staging and production

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#258] opened 2016-04-03 02:06 UTC
On the school overview, there are difference in discipline incidents between the staging and production environments.  The staging environment doesn't have any students with more than one discipline incident.

From filtering on the overview page, and then comparing the details of three students between production and staging, it looks like staging has only the oldest discipline incident shown, while production has more recent ones as well.

**Comment by alexsoble** [comment] 2016-04-04 16:49
@kevinrobinson Investigating!

**Comment by alexsoble** [comment] 2016-04-04 17:01
Yes, this is a huge discrepancy.

__PRODUCTION:__

`DisciplineIncident.count # => 1114`

__STAGING:__

`DisciplineIncident.count # => 265`

My initial suspicion is that this is an issue with the import process.

**Comment by alexsoble** [comment] 2016-04-04 17:29
Can confirm that the staging site is undercounting discipline incidents. 

Looked up a student with a high number of discipline incidents and found more records in the export file than were being imported by the import process to a fresh staging site.

**Comment by alexsoble** [comment] 2016-04-04 17:48
Confirmed bug in `BehaviorRow`, has to do with this: http://apidock.com/rails/ActiveRecord/Relation/first_or_initialize

The `BehaviorRow` code was selected the first incident per school year instead of searching by the provided attributes and creating new incidents.

Will document, spec, and fix. 

Thanks for catching this @kevinrobinson!  

🌈

**Comment by alexsoble** [comment] 2016-04-04 18:08
Reopening until the import tasks have been run and the two environments look the same!

**Comment by alexsoble** [comment] 2016-04-04 18:20
Re-running the import task in both environments has shrunk the gap significantly, but there's still a difference in discipline incident database counts between the two environments. 

Let's see if resolving #9 will bring that gap down to zero, since right now the two environments have slightly different student populations due to active student drift over time.

**Comment by alexsoble** [comment] 2016-04-04 19:50
After accounting for inactive students (#9), discipline incident breakdown is the same between production and staging environments on the school overview page.

💥

**Closed by alexsoble** 2016-04-04 19:50 UTC
Labels: data-import, developer experience

**Comment by kevinrobinson** [comment] 2016-04-04 23:09
:boom: awesome work @alexsoble!
