### ISSUE TITLE
New SHS Student Not Showing Up in Insights (but is in Aspen)

### ISSUE THREAD

**Issue by snoopyuri** [studentinsights/studentinsights#1104] opened 2017-09-27 12:29 UTC
At first we thought it's because she didn't have a SASID yet.  Then we fixed that and she's still not showing up, even though she looks ok in Aspen.  If you are able to dig into the issue, please email me (Uri) and I'll give you the student's name and the screenshot from Aspen.

**Comment by jhilde** [comment] 2017-09-27 14:02
Took a look. The student has been properly imported into Student Insights. It looks like the educator (schoolwide access) does not have the student's information in the student_searchbar_json. 

Is it possible that the part of the importer responsible for generating the cached json didn't run? @alexsoble

**Comment by alexsoble** [comment] 2017-09-28 18:29
@jhilde — we removed that caching here: https://github.com/studentinsights/studentinsights/pull/1051. We didn't consider students entering/leaving the system when we removed that caching from the import process. So I think it's time to restore the caching! @jhilde Thanks for digging in and finding the root cause of this! In the meantime I'll kick off another job to recache for all educators.

**Comment by jhilde** [comment] 2017-09-28 18:38
@alexsoble — Ah that makes sense. There is certainly some students coming in the district all the time and there's even more adding and dropping of classes.

**Comment by jhilde** [comment] 2017-09-29 19:31
This individual student is now showing up in the searchbar. Now that the caching was added back to the import.

Closing...looks like the educator who needed access has done a great job of adding notes!

**Closed by jhilde** 2017-09-29 19:31 UTC

**Comment by snoopyuri** [comment] 2017-09-29 22:12
Just checked on my end and the student is showing up.  Thanks for this and yes, the counselor is very invested in Insights so him seeing that the issue got addressed quickly is a big win!  Thanks everyone.
