### ISSUE TITLE
Fix service saving bug

### ISSUE THREAD

**Issue by alexsoble** [studentinsights/studentinsights#1387] opened 2018-01-18 04:21 UTC
Via Rollbar:

```
NoMethodError: undefined method `<' for nil:NilClass
  File "/app/app/controllers/students_controller.rb", line 110, in service
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/action_controller/metal/basic_implicit_render.rb", line 4, in send_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/actionpack-5.1.3/lib/abstract_controller/base.rb", line 186, in process_action
  File "/app/vendor/bundle/ruby/2.3.0/gems/scout_apm-2.1.29/lib/scout_apm/instruments/action_controller_rails_3_rails4.rb", line 68, in process_action
```

**Comment by kevinrobinson** [comment] 2018-01-20 17:02
Looking at https://rollbar.com/somerville-teacher-tool/somerville-teacher-tool/items/84/occurrences/36048477760/, the problem is that the client posted an invalid date.  Here's the relevant excerpted data:
```
{
  "service": {
    "estimated_end_date": "Invalid date",
  }
}
```

**Comment by kevinrobinson** [comment] 2018-01-20 17:08
I can reproduce this locally by just not filling out the end date.  this is a duplicate of https://github.com/studentinsights/studentinsights/issues/1307, closing this and moving discussion over there.

**Closed by kevinrobinson** 2018-01-20 17:08 UTC
Labels: bug
