### ISSUE TITLE
Fix bug with ATP errors in WSNS homerooms

### ISSUE THREAD

**Issue by kevinrobinson** [studentinsights/studentinsights#352] opened 2016-04-13 02:56 UTC
```
2016-04-13T02:55:02.875235+00:00 app[web.1]: Completed 500 Internal Server Error in 201ms (ActiveRecord: 72.9ms)
2016-04-13T02:55:02.886385+00:00 app[web.1]:
2016-04-13T02:55:02.886394+00:00 app[web.1]: NoMethodError (undefined method `id' for nil:NilClass):
2016-04-13T02:55:02.886395+00:00 app[web.1]:   app/models/intervention.rb:53:in `most_recent_atp'
2016-04-13T02:55:02.886395+00:00 app[web.1]:   app/models/student.rb:215:in `most_recent_atp_hours'
2016-04-13T02:55:02.886396+00:00 app[web.1]:   app/controllers/homerooms_controller.rb:50:in `fat_student_hash'
2016-04-13T02:55:02.886397+00:00 app[web.1]:   app/controllers/homerooms_controller.rb:11:in `block in show'
2016-04-13T02:55:02.886397+00:00 app[web.1]:   app/controllers/homerooms_controller.rb:11:in `show'
2016-04-13T02:55:02.886398+00:00 app[web.1]:
2016-04-13T02:55:02.886399+00:00 app[web.1]:
```

**Comment by alexsoble** [comment] 2016-04-13 14:32
This issue was caused by a missing database constant.

Fixed by running `InterventionType.seed_somerville_intervention_types` in the staging environment console. 

The `InterventionType` class is marked as "Deprecated." It is deprecated in the sense that it's not possible to create new Interventions in Student Profile V2 — those have been superseded by new models, `Service` and `EventNote`. But old Interventions are still displayed in the student feed as deprecated notes/interventions:

```
# StudentsController 

  def student_feed(student)
    {
      event_notes: student.event_notes.map {|event_note| serialize_event_note(event_note) },
      services: {
        active: student.services.active.map {|service| serialize_service(service) },
        discontinued: student.services.discontinued.map {|service| serialize_service(service) }
      },
      deprecated: {
        notes: student.student_notes.map { |note| serialize_student_note(note) },
        interventions: student.interventions.map { |intervention| serialize_intervention(intervention) }
      }
    }
  end
```

So we can't blow up the Intervention / InterventionTypes classes yet until we write a proper migration.

What we can do is remove the `Intervention` class from the roster view. The roster view includes a column that lets a teacher bulk-add interventions for her/his students. This feature should be deleted for two reasons:

1. It uses on an `Intervention` class that is now deprecated.
2. We are focusing on services/interventions being added in the context of MTSS and SST meetings; we are explicitly not focusing on classroom teachers entering data right now.

Will break remove-interventions-from-roster into a separate issue.

**Closed** 2016-04-13 14:35 UTC
Labels: bug

**Comment by alexsoble** [comment] 2016-04-13 18:45
Removing bulk intervention adding from the roster was a good step! Now no more deprecated Interventions can enter the system.

But there's one more step to take in the intervention-code-removal-in-roster arena!

The bug referenced above was caused by a missing database constant referring to the ATP (After School Tutoring) intervention. This intervention was surfaced on the roster page as an experimental feature but was never fully productionized. We should delete this because:

1. The data is not up to date, meaning not useful.
2. The `Intervention` category it calls is deprecated.
3. It can potentially break things if the required database constants are missing, as in the above example.
